shell:
 program: /usr/local/bin/zsh
 args:
  - --login

font:
  normal:
    family: Monaco
  bold:
    family: Monaco
  italic:
    family: Monaco
  size: 15.0

background_opacity: 0.8


# Color Scheme (copied from https://github.com/eendroroy/alacritty-theme/blob/master/themes/snazzy.yaml)
# This is distributed in the Apache License 2.0.
# Colors (Snazzy)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xeff0eb'

  # Normal colors
  normal:
    black:   '0x282a36'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'

  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'
