[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowHidden = 1
    nnoremap <C-o> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \   '_' : {
    \       'runner' : 'vimproc',
    \       'runner/vimproc/updatetime' : 10,
    \       'outputter/buffer/split' : ':botright 8sp',
    \   },
    \ }
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
