[[plugins]]
repo = 'kateinoigakukun/deoplete-swift'
on_ft = 'swifhook_sourcet'
hook_source = '''
    let g:deoplete#sources#swift#source_kitten_binary = '/usr/local/bin/sourcekitten'
    let g:deoplete#sources#swift#daemon_autostart = 1
    let g:deoplete#sources#swift#sdk = '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'
    let g:deoplete#sources#swift#target = 'arm64-apple-ios10.0'
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = 'python'
hook_source = '''
    let g:jedi#force_py_version = 3
    let g:jedi#completions_enabled = 1
    let g:jedi#auto_vim_configuration = 1
'''


[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'


[[plugins]]
repo = 'apple/swift'
on_ft = 'swift'
rtp = 'utils/vim'


[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_autowrite = 1
'''

[[plugins]]
repo = 'kateinoigakukun/previm'
on_ft = 'markdown'
hook_source = '''
    let g:previm_enable_realtime = 1
    let g:previm_show_header = 0
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['previm']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'godlygeek/tabular'
on_i = 1

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'mattn/webapi-vim'

